"""
If the pipeline up to now has been completed
There should be a series of 3 atlases
each of which has been generated by a different method of dimensionality reduction
Each atlas consists of a series of centroids and of their 10,000 closest neighbors,
embedded in a low dimensional space (default 50 dimensions)

Given as each point corresponds to a prompt, we can interpret those embeddings proceduraly.
The goal of this script is to perform the preprocesing, before shipping the natural language to a commercial LLM for interpretation.

For any given atlas, the method is about the same:

1. Load the list of closest neighbors for each centroid, which should be in results/Balltree/nearest_<clustering.k-nearest_large>_neighbors_indices_layer_<model.layer_for_activation>_n_centroids_<Clustering.n_centroids>.npy
Where all values marked with <> are sourced from config. See paths.py for more details.

2.Load the embeddings of the neighbors of the centroids, which should be in results/<method>_atlas_<dimensionality.n_components>D/<dimensionality.n_components>D/centroid_<centroid_num:4.0d0>_embeddings_<dimensionality.n_components>D.npy
Where all values marked with <> are sourced from config, apart from <method> which is either "iso", "pca" or "autoencoder" depending on which atlas we are processing at the moment

3. Perform PCA on the embeddings, TO THE SAME DIMENSIONALITY. We are not reducing dimensionality further, but we are interested in directions of maximal variance.

4.Produce <dimensionality.n_components> arrays sorting the indices associated with the embeddings by their projection on each of the PCA components, in descending order. 
Now, it is important to note that the indicess here are **global**, that is, the indices are correlated to the indices of the activations\
in the TOTAL dataset, even if only a fraction of it appeaars in any given centroid.
So, when we produce the arrays, they are filled with global indices

To recap the index shenanigans:
When we pull the list of closesnt neighbors for a given centroid, we are given a list
[a_0,a_1,a_2,...a_9999] where of course a_i does not necessarily equal i.

denote A_i the activation associated with index a_i, and denote the encoding function as E.
the embedding array for the neighbors of the centroid is then given by
[E(A_0),E(A_1),E(A_2),...E(A_9999)]

WHen we project on principal comopnent j, we get a list of projections 
[p_0,p_1,p_2,...p_9999] where p_i is the projection of E(A_i) on the jth principal component.

Now we sort, to end up with
[p_{i_0},p_{i_1},p_{i_2},...p_{i_9999}] where p_{i_k} is the kth largest value in the list of projections, and i_k is the index associated with that value.

We finally want to translate this back into global indices, so we produce the list
[a_{i_0},a_{i_1},a_{i_2},...a_{i_9999}] which is the list of global indices sorted by their projection on the jth principal component.

We prodce <dimensionality.n_components> arrays like this, one for each principal component, and we save them in results/<method>_sorted_by_projection/<dimensionality.n_components>D/centroid_<centroid_num:4.0d0>/sorted_indices_by_projection_on_PCA_component_<component_num:3.0d0>.npy

Repeat for every centroid, and for every atlas. """

import os
import sys
import argparse
from datetime import datetime
from pathlib import Path

import numpy as np
from sklearn.decomposition import PCA

# Add src to path for imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src import paths
from src.config_manager import load_config, add_config_argument
from src.utils.common import load_neighbor_indices


def preprocess_atlas(
	method: str,
	neighbor_indices: np.ndarray,
	config,
	n_components: int
) -> None:
	"""Preprocess embeddings for a single atlas (method).
    
	Args:
		method: Dimensionality reduction method ("iso", "pca", or "autoencoder")
		neighbor_indices: Array of shape (n_centroids, k_nearest) with global indices
		config: Configuration object
		n_components: Number of dimensions for embeddings
	"""
	n_centroids = config.clustering.n_centroids
    
	print(f"\n{'='*80}")
	print(f"[{datetime.now()}] Processing {method.upper()} atlas...")
	print(f"{'='*80}")
    
	for centroid_idx in range(n_centroids):
		print(f"\n[{datetime.now()}] Processing centroid {centroid_idx}/{n_centroids-1}...")
        
		# Load embeddings for this centroid
		if method == "iso":
			embeddings_path = paths.get_isomap_embeddings_path(centroid_idx, n_components)
		elif method == "pca":
			embeddings_path = paths.get_pca_embeddings_path(centroid_idx, n_components)
		elif method == "autoencoder":
			embeddings_path = paths.get_autoencoder_embeddings_path(centroid_idx, n_components)
		else:
			raise ValueError(f"Unknown method: {method}")
        
		if not embeddings_path.exists():
			print(f"[{datetime.now()}] WARNING: Embeddings not found at {embeddings_path}, skipping...")
			continue
        
		embeddings = np.load(embeddings_path)
		print(f"[{datetime.now()}] Loaded embeddings with shape {embeddings.shape}")
        
		# Get global indices for this centroid's neighbors
		global_indices = neighbor_indices[centroid_idx]
        
		# Verify consistency
		if embeddings.shape[0] != len(global_indices):
			print(f"[{datetime.now()}] ERROR: Shape mismatch! Embeddings: {embeddings.shape[0]}, "
				  f"Indices: {len(global_indices)}. Skipping centroid.")
			continue
        
		# Perform PCA on the embeddings to the same dimensionality
		# This gives us the directions of maximal variance
		print(f"[{datetime.now()}] Performing PCA with {n_components} components...")
		pca = PCA(n_components=n_components)
		pca_embeddings = pca.fit_transform(embeddings)
        
		print(f"[{datetime.now()}] PCA explained variance ratio (first 5 components): "
			  f"{pca.explained_variance_ratio_[:5]}")
        
		# For each PCA component, sort indices by projection
		for pca_component in range(n_components):
			# Get projections on this component
			projections = pca_embeddings[:, pca_component]
            
			# Sort in descending order (largest projections first)
			# argsort gives ascending, so we negate or use [::-1]
			sorted_local_indices = np.argsort(projections)[::-1]
            
			# Map back to global indices
			sorted_global_indices = global_indices[sorted_local_indices]
            
			# Save to file
			output_path = paths.get_sorted_indices_path(method, centroid_idx, n_components, pca_component)
			output_path.parent.mkdir(parents=True, exist_ok=True)
			np.save(output_path, sorted_global_indices)
            
			if pca_component < 3:  # Log first few components
				print(f"[{datetime.now()}]   PC {pca_component}: saved sorted indices to {output_path.name}")
        
		print(f"[{datetime.now()}] Completed centroid {centroid_idx} - saved {n_components} sorted index arrays")
    
	print(f"\n[{datetime.now()}] Finished processing {method.upper()} atlas")


def main():
	"""Main preprocessing pipeline."""
	parser = argparse.ArgumentParser(
		description="Preprocess embeddings by sorting along PCA components"
	)
	add_config_argument(parser)
	parser.add_argument(
		"--methods",
		type=str,
		nargs="+",
		default=["iso", "pca", "autoencoder"],
		choices=["iso", "pca", "autoencoder"],
		help="Methods to process (default: all three)"
	)
	args = parser.parse_args()
    
	# Load configuration
	config = load_config(args.config)
    
	print(f"{'='*80}")
	print(f"PREPROCESSING EMBEDDINGS")
	print(f"{'='*80}")
	print(f"[{datetime.now()}] Configuration loaded:")
	print(f"  - n_centroids: {config.clustering.n_centroids}")
	print(f"  - k_nearest: {config.clustering.k_nearest_large}")
	print(f"  - layer: {config.model.layer_for_activation}")
	print(f"  - n_components: {config.dimensionality.n_components}")
	print(f"  - Methods to process: {args.methods}")
    
	# Construct neighbor indices filename
	k_nearest = config.clustering.k_nearest_large
	layer = config.model.layer_for_activation
	n_centroids = config.clustering.n_centroids
	indices_filename = f"nearest_{k_nearest}_neighbors_indices_layer_{layer}_n_centroids_{n_centroids}.npy"
    
	print(f"\n[{datetime.now()}] Loading neighbor indices from: {indices_filename}")
    
	# Load neighbor indices
	neighbor_indices = load_neighbor_indices(indices_filename)
	print(f"[{datetime.now()}] Neighbor indices shape: {neighbor_indices.shape}")
    
	# Get dimensionality
	n_components = config.dimensionality.n_components
    
	# Process each method
	for method in args.methods:
		try:
			preprocess_atlas(
				method=method,
				neighbor_indices=neighbor_indices,
				config=config,
				n_components=n_components
			)
		except Exception as e:
			print(f"\n[{datetime.now()}] ERROR processing {method} atlas: {e}")
			import traceback
			traceback.print_exc()
			print(f"[{datetime.now()}] Continuing with next method...")
    
	print(f"\n{'='*80}")
	print(f"[{datetime.now()}] Preprocessing complete!")
	print(f"{'='*80}")


if __name__ == "__main__":
	main()
"""